### ISSUE TITLE
tags are applied inconsistenly 

### ISSUE THREAD

**Issue by runrin** [manolomartinez/greg#100]
For some reason the artist is not being tagged on some files in this feed:

`~/.config/greg/greg.conf`
```
...
[the-adventure-zone]

Tag = yes

tag_artist = The Adventure Zone
tag_album = The Adventure Zone
tag_date = {date}

file_to_tag = {filename_title}.mp3
downloadhandler = wget -q {link} -O {directory}/{filename_title}.mp3
...
```

`~/.local/share/greg/data/data`
```
...
[the-adventure-zone]
url = https://feeds.simplecast.com/cYQVc__c
date_info = available
...
```

`ffprobe Ep__1__Here_There_Be_Gerblins___Chapter_One.mp3`

```
  Metadata:
    title           : Ep. 1: Here There Be Gerblins - Chapter One
    album           : The Adventure Zone
    date            : 2014-12-03
    genre           : Podcast
```

`ffprobe The_Adventure_Zone__Graduation_Ep__30__Take_Your_Firbolg_to_Work_Day.mp3`
```
  Metadata:
    title           : The Adventure Zone: Graduation Ep. 30: Take Your Firbolg to Work Day
    artist          : The Adventure Zone
    album           : The Adventure Zone
    date            : 2020-12-10
    encoder         : Lavf58.29.100
    genre           : Podcast
```

Perhaps I am missing something obvious? If you need more information, let me know. Thanks :)

**Comment by manolomartinez** [comment]
Hi, I think the changes I've made to [this branch](https://github.com/manolomartinez/greg/compare/issue100?expand=1) fix your issue. Would you be so kind of checking whether that's the case?

Thanks,
Manolo
