### ISSUE TITLE
Feature request: force remove

### ISSUE THREAD

**Issue by HeuristicPerson** [manolomartinez/greg#112]
First of all, great piece of software, many thanks for it. I just discovered it few days ago and at the moment I'm in the process of creating a small docker image to automatically download my subscriptions.

A feature I'm missing is the ability to remove a subscription without any question. My intent is to add my suscriptions to a txt file and run a periodic script that adds and removes the desired podcasts.

Regards and many thanks again.

**Comment by manolomartinez** [comment]
Could you please check whether the above PR works for you?

**Comment by manolomartinez** [comment]
Also, if at some point you'd be willing to share your dockerfile, that might be a nice addition to the README, perhaps.

**Comment by HeuristicPerson** [comment]
Morning, Manolo

Sure, I'll try it and I'll share my dockerfile. On the other hand, I don't remember the exact reason but in the end I created my own RSS downloader written in Python which is what I'm using at the moment.

Regards
