### ISSUE TITLE
problems with a few podcasts since uprade from Ubuntu 16.04 to 20.04

### ISSUE THREAD

**Issue by thomasboehm** [manolomartinez/greg#114]
Since rebuilding my server I have problems with a few podcasts. I freshly installed Ubuntu 20.04 Server, installed greg with `--user` and restored .config/greg, .local/share/greg and my helper script.

I don't know whether the problem lies with the new Ubuntu version or with the newer greg version. I removed the podacasts which threw an error and `greg sync` works again. Then I tried to add the other podcasts one by one but get the following error

``` Traceback (most recent call last):
  File "/home/frontend/.local/bin/greg", line 8, in <module>
    sys.exit(main())
  File "/home/frontend/.local/lib/python3.8/site-packages/greg/parser.py", line 138, in main
    function(vars(args))
  File "/home/frontend/.local/lib/python3.8/site-packages/greg/commands.py", line 187, in sync
    msg = ''.join(["I cannot sync ", feed, " just now: ",
TypeError: sequence item 1: expected str instance, Feed found
```

Steps to reproduce:

`greg add "TWIT Floss Weekly" https://feeds.twit.tv/floss.xml`
`greg check -f "TWIT Floss Weekly"`

This lists 10 Episodes. But when I run `greg download 0` nothing happens, not even an error. When I run `greg sync` again I get the error above.

**Comment by manolomartinez** [comment]
I can't reproduce this, as it is. Are you updated up to the latest commit here, or just the latestsrelease? If the latter, would you mind updating to the latest commit? Like so:

`pip install git+https://github.com/manolomartinez/greg`

Please let me know if the problem persists after doing that.

**Comment by dustinreeves** [comment]
so just so you know, i had to issue a "pip3 install greg"

**Comment by manolomartinez** [comment]
> i had to issue a "pip3 install greg"

Hi, Dustin. You had to issue that command in order to do what? Is this related to the above issue?

Thanks

**Comment by thomasboehm** [comment]
> I can't reproduce this, as it is. Are you updated up to the latest commit here, or just the latest release? If the latter, would you mind updating to the latest commit? Like so:
> 
> `pip install git+https://github.com/manolomartinez/greg`
> 
> Please let me know if the problem persists after doing that.

This seemed to have solved the problem.
