### ISSUE TITLE
Not all feeds works, ie soundcloud feeds, it seems

### ISSUE THREAD

**Issue by rosell-dk** [manolomartinez/greg#117]
The following sound cloud feed doesn't work:
```
greg add feed1 https://feeds.soundcloud.com/users/soundcloud:users:254049939/sounds.rss
greg check -f feed1
```
Result: Nothing

Actually, I don't have much luck in finding feeds that works.
The following doesn't work either:
https://www.spreaker.com/show/4553892/episodes/feed

The PhilosophyBites feed however works fine.

**Comment by rosell-dk** [comment]
I'm assuming the feeds cannot be parsed due to some unsupported syntax.

A workaround could be to transform the feed into something that greg can work with

**Comment by manolomartinez** [comment]
You get no results, no error, nothing?

**Comment by rosell-dk** [comment]
Correct. Does these URLs work for you?

**Comment by manolomartinez** [comment]
No, they throw an `SSL: CERTIFICATE_VERiFY_FAILED error. Where do these urls come from?

**Comment by rosell-dk** [comment]
For example here: https://danske-podcasts.dk/category/kids-family

radionauterne.dk also links to soundcloud

**Comment by rosell-dk** [comment]
So you see a failure? But SSL certificate is deemed valid by Chrome

**Comment by rosell-dk** [comment]
I'm on the hunt for a service for transforming feeds on the fly.
I found https://feed2json.org, which can convert feed to json like this: 
https://feed2json.org/convert?url=https%3A%2F%2Fwww.spreaker.com%2Fshow%2F4553892%2Fepisodes%2Ffeed

If I can just find a reverse service...

**Comment by manolomartinez** [comment]
> So you see a failure? But SSL certificate is deemed valid by Chrome

Sorry, that had nothing to do with the feeds we were discussing. Now apparently urllib has decided it cannot trust anything or anyone :/ Let me fix that first and I'll get back to this issue.

**Comment by rosell-dk** [comment]
So sorry. It was a typo - I entered the wrong URL!
