### ISSUE TITLE
Does this tool re-download deleted podcast episodes?

### ISSUE THREAD

**Issue by WolfgangDpunkt** [manolomartinez/greg#122]
That sounds very promising.
But does your tool re-download deleted podcast episodes?
I have not seen an "skip already downloaded, but meanwhile deleted files" option in the very well written documentation.

Before I try it myself, I'll just ask, possibly as a suggestion to add this info in the readme ;-)

For me, this is the most important feature, because I remove episodes after finished listening to it, and it would be fatal if they are then downloaded again.
Thank you very much!

**Comment by manolomartinez** [comment]
Hi, greg won't download again an episode if it has done it once already---but it doesn't check what you do with your file once you've downloaded it. You can delete it, listen to it or not, and greg won't know or care.

Hope this helps,
Manolo
