### ISSUE TITLE
YouTube downloader

### ISSUE THREAD

**Issue by manolomartinez** [manolomartinez/greg#17]
Hey, @FilipBB, can you help me understand why something like this is needed? What it brings that greg currently cannot do?

I was thinking that perhaps with a bit extra work I could make something more general than a mere add-on for YT. Once I understand what it is doing.

**Comment by PodCol** [comment]
Hi
I tried to use the ignoreenclosures option, but greg doesn't download anything while syncing. It works when I use greg check / greg download 0 though.

**Comment by manolomartinez** [comment]
Yep, I see what the problem is. Please install this test version, and let me know if it works:

    pip install --index-url https://testpypi.python.org/pypi/ greg

**Comment by PodCol** [comment]
It does!

I use greg daily for more than two years now, and I really like it. Thank you for your work.

**Comment by manolomartinez** [comment]
Why didn't I close this? The issue is fixed, isn't it? Oh, well.
