### ISSUE TITLE
greg data save creates empty files instead - also cannot update forward from past date

### ISSUE THREAD

**Issue by xHN35RQ** [manolomartinez/greg#27]
With greg on Ubuntu 14.04 when I run an edit the data is not saved, for example running:

`greg edit 'Name of Podcast' -d 2015-05-15`

Instead of saving data into the file `~/.local/share/greg/data/Name of Podcast` it just wipes the file and leaves it empty.

Any idea why this is happening?

**Comment by manolomartinez** [comment]
Hi, please see if the fix I've pushed does it.

Thanks for reporting!

Manolo

**Comment by xHN35RQ** [comment]
Perfect, thanks for fixing!!

**Comment by xHN35RQ** [comment]
Oops, now it won't update to a newer date. For instance, setting a Podcast back to a date in Jan 2015 works fine, but I cannot then update that same Podcast forward to March 2015. So I can date backwards but not forwards.

**Comment by xHN35RQ** [comment]
Oops, now it won't update to a newer date. For instance, setting a Podcast back to a date in Jan 2015 works fine, but I cannot then update that same Podcast forward to March 2015. So I can date backwards but not forwards.

**Comment by manolomartinez** [comment]
All right, I think greg now behaves as it should every time. But please do check it and let me know if I'm still missing something!

Thanks
M

**Comment by xHN35RQ** [comment]
Yep it's works well now, I can date forwards and backwards in time. Thanks again!! :+1: :trophy:

**Comment by xHN35RQ** [comment]
Yep it's works well now, I can date forwards and backwards in time. Thanks again!! :+1: :trophy:
