### ISSUE TITLE
please update pypi 

### ISSUE THREAD

**Issue by xHN35RQ** [manolomartinez/greg#28]
https://pypi.python.org/pypi/Greg is still on 0.3.0 and it would be nice to have an update to 0.4.0 including the latest commit: https://github.com/manolomartinez/greg/commit/4f8b59ede5a8509f0de9f226d0996abce730f9bf

let me know is there anything I can do to help make this happen.

thanks again for this great tool!!

**Comment by manolomartinez** [comment]
Done, it's the new 0.4.3 release. Please check whether everything's working

**Comment by manolomartinez** [comment]
r

**Comment by xHN35RQ** [comment]
Thanks for pushing the update, However I encounter the following problems:

Depending on how I run greg I'll instead see one of the following: 

`bash: /usr/local/bin/greg: /bin/python3: bad interpreter: No such file or directory`

    Traceback (most recent call last):
      File "/usr/local/bin/greg", line 17, in <module>
        from greg.gregparser import main 
    ImportError: No module named 'greg'
