### ISSUE TITLE
pypi 0.4.3: "#!/usr/bin/env python3" gets changed to "#!/bin/python" on install

### ISSUE THREAD

**Issue by xHN35RQ** [manolomartinez/greg#29]
Thanks for pushing the update to pypi, However I encounter the following problem:

When I run greg I'll see the following: 

`bash: /usr/local/bin/greg: /bin/python3: bad interpreter: No such file or directory`

**Comment by manolomartinez** [comment]
Huh. I'm not seeing any problems here. You install by running `pip install greg`, don't you? What happens next?

**Comment by Narrat** [comment]
I would ask additionally for:
What distro?
Got /bin and /usr/bin merged?
What result for "whereis python3?

At least the bad interpreter error looks like /bin and /usr/bin are separate things

**Comment by manolomartinez** [comment]
Yep, what Narrat said :)

**Comment by xHN35RQ** [comment]
Oops sorry. Yes, installed via `pip install greg`

* Ubuntu 14.04
* How do I tell if `/bin` and `/usr/bin` are merged?
* result for `whereis python3`:
    python3: /usr/bin/python3.4-config /usr/bin/python3.4m-config /usr/bin/python3.4 /usr/bin/python3 /usr/bin/python3.4m /etc/python3.4 /etc/python3 /usr/lib/python3.4 /usr/lib/python3 /usr/bin/X11/python3.4-config /usr/bin/X11/python3.4m-config /usr/bin/X11/python3.4 /usr/bin/X11/python3 /usr/bin/X11/python3.4m /usr/local/lib/python3.4 /usr/include/python3.4 /usr/include/python3.4m /usr/share/python3 /usr/share/man/man1/python3.1.gz

**Comment by Narrat** [comment]
>How do I determine if /bin and /usr/bin are merged? (I don't think they are...)

If /bin is a link to /usr/bin for example

One point of notice. iirc greg doesn't run under python2 (hence the encoding issue). Changing in the python2 environment the interpreter to py3 causes the problem, that it searches for the py3 module and cannot find it.

If running the correctly py3 pip version producing the error for file not found. hm
Wonderous why the /usr/bin/env check returns the wrong path, as your python3 interpreter is installed in /usr/bin (and if /bin isn't a link to /usr/bin this will fail).
Something is setting the wrong env (or at least looks like that)
You could see what happens if you change 
>#!/usr/bin/env python3

to
>#!/usr/bin/python3

**Comment by xHN35RQ** [comment]
Ok, my /bin and /usr/bin are separate directory.

I just did a fresh install of greg from pypi using `pip install greg` again receive the following error upon run: `bash: /usr/local/bin/greg: /bin/python: bad interpreter: No such file or directory`

So I looked in the file of /usr/local/bin/greg and see on first line: `#!/bin/python` and NOT `#!/usr/bin/env python3` If I change it back to `#!/usr/bin/env python3` or even `#!/usr/bin/python3` everythign works fine!!

So this is a problem because I do not have /bin/python at all on my Ubuntu. So why on installation does that first line get changed to `#!/bin/python` ???

**Comment by xHN35RQ** [comment]
I think `setuptools` might be mangling the shebang line?

**Comment by manolomartinez** [comment]
Thanks for the report, I will try to understand what's going on and get back to you.

**Comment by manolomartinez** [comment]
All right, I've uploaded a test package to testpypi in which I only use setuptools. If you can, please install it with

    pip install --index-url https://testpypi.python.org/pypi/ greg

and let me know if this behaves.

**Comment by xHN35RQ** [comment]
Yes! That works well for me, it installs correctly, and launches correctly. And the shebang of /usr/local/bin/greg is `#!/usr/bin/python3`

Thanks again!

**Comment by xHN35RQ** [comment]
Is there anything you need from me to help close this issue?

**Comment by manolomartinez** [comment]
> Is there anything you need from me to help close this issue or help push the test version live?

Nudging me from time to time works fine ;)
Done!
M

**Comment by xHN35RQ** [comment]
Awesome, thanks again! I updated and everything is working well.
