### ISSUE TITLE
Allow installation as user

### ISSUE THREAD

**Issue by kwbr** [manolomartinez/greg#3]
Installing as a user is not possible at the moment because /etc/greg.conf is required and the setup.py tries to install it at this fixed place. Please consider a plain user install (pip install --user ...)

**Comment by manolomartinez** [comment]
Some of the latest changes I have made should allow user install from pip -- I think! If you are still using greg, or interested in it, please give it a go.

**Comment by xHN35RQ** [comment]
#41 should be able to close this issue.

**Comment by manolomartinez** [comment]
I think this issue is solved now, as you say. Closing.
