### ISSUE TITLE
homebrew package missing

### ISSUE THREAD

**Issue by vigilancer** [manolomartinez/greg#38]
It would be nice to have homebrew package for greg.

**Comment by manolomartinez** [comment]
I am not at all familiar with the OSX environment, but I'd be happy to consider a PR about this.

**Comment by xHN35RQ** [comment]
Homebrew has python3. I see no reason to package greg for homebrew when you can do:

`brew install python3` then `pip3 install --user greg`

**Comment by manolomartinez** [comment]
Thanks, that sounds sensible. Closing, then.
