### ISSUE TITLE
running 'greg' alone crashes:

### ISSUE THREAD

**Issue by mfeif** [manolomartinez/greg#42]
```
~$ greg
Traceback (most recent call last):
  File "/home/mjf/.local/bin/greg", line 9, in <module>
    load_entry_point('Greg==0.4.5', 'console_scripts', 'greg')()
  File "/home/mjf/.local/lib/python3.4/site-packages/greg/gregparser.py", line 113, in main
    args.func(vars(args))
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by xHN35RQ** [comment]
I confirm this. Installing from https://github.com/manolomartinez/greg/commit/9c223ca57f6f1dcae9b4a1bceafe769b7d2c41a2

**Comment by xHN35RQ** [comment]
This happens because argparse is expecting command line arguments but when none are passed func is empty and it throws an error.

One way to fix is set a default arg when calling greg without any arguments.

**Comment by xHN35RQ** [comment]
Ok that fixes it for me on my local Greg install.

**Comment by xHN35RQ** [comment]
Yeeeah, that didn't fix it. Ignore that commit.

**Comment by xHN35RQ** [comment]
Nope I was right after all, that commit did fix it. I just found another bug: #43

**Comment by manolomartinez** [comment]
[This](https://github.com/manolomartinez/greg/commit/945e35a9f2f6618daa2a747f684f90754b7ecff2) is a slightly cleaner way to do it, I reckon.

**Comment by xHN35RQ** [comment]
It is indeed.
