### ISSUE TITLE
greg add IsADirectoryError - missing global conf file

### ISSUE THREAD

**Issue by xHN35RQ** [manolomartinez/greg#43]
```
Traceback (most recent call last):
  File "/home/nick/.local/bin/greg", line 9, in <module>
    load_entry_point('Greg==0.4.5', 'console_scripts', 'greg')()
  File "/home/nick/.local/lib/python3.4/site-packages/greg/gregparser.py", line 117, in main
    args.func(vars(args))
  File "/home/nick/.local/lib/python3.4/site-packages/greg/greg.py", line 629, in add
    with open(session.data_filename, 'w') as configfile:
IsADirectoryError: [Errno 21] Is a directory: '/home/nick/.local/share/greg/data'
```

**Comment by xHN35RQ** [comment]
Ok, so installing greg from git using `pip install --user git+https://github.com/manolomartinez/greg.git" doesn't create the following directory:

/home/nick/.local/lib/python3.4/site-packages/greg/data/greg.conf

Which means there is there is no global `greg.conf`

If greg.conf is missing greg doesn't know where to find the default data directory which in this case is '/home/nick/.local/share/greg/data`

So this commit bf15fd3 fixes the fallback to this location. Let me know if this is a good way to handle this or not.

**Comment by manolomartinez** [comment]
Ugh, yes, thanks for opening this issue, Nick.

The right way to do it, I think, is to get setuptools to install package data as we intended. This is a famous mess, but I think I got it working now.

[This commit](https://github.com/manolomartinez/greg/commit/3c23585f8d21d9d321cc0c076ac74b65adb31bf9) accomplishes it, I think.

**Comment by xHN35RQ** [comment]
Works perfect! Thanks.
