### ISSUE TITLE
Not downloading all episodes from feed (revolutionspodcast.com)

### ISSUE THREAD

**Issue by quite** [manolomartinez/greg#45]
Just trying out greg for the first time here, this url: `http://www.revolutionspodcast.com/rss.xml`
greg only gets downloads "4.10- The Third Commission", but 10 episodes are listed with `greg check`.
Also, `greg download` doesn't manage to get them either. (by the way, how does greg download know which feed to select from?)

**Comment by manolomartinez** [comment]
So, you add the feed with `greg add`? Then try to `sync`? Please let me know the exact sequence of commands you used.

Greg, by default, only downloads the most recent entry the first time it syncs (you can change this default behavior), but I see that 4.10 is not the latest entry in that podcast.

As for `greg download`, you need to specify which number(s) you want to download. E.g., `greg download 0-9`. Check out `greg download --help`.

**Comment by quite** [comment]
Yeah, like so:

    $ greg add revolutions http://www.revolutionspodcast.com/rss.xml
    $ greg sync
    Checking revolutions...
    Downloading 4.10- The Third Commission -- 4.10-The_Third_Commission_Master.mp3
    Done
    $

- -
Yes, but the numbers are local to each feed, right?

**Comment by manolomartinez** [comment]
I've looked into this podcast, and it doesn't carry the links to the actual audio file in a way that greg (or any other aggregator, I would say) can understand: they only appear within the description of each entry. Greg does not (and, I think, should not) scrape descriptions for links.

The only entry that is constructed according to the RSS spec is 4.10. Why only that one, beats me.

> Yes, but the numbers are local to each feed, right?

In fact, the numbers in `download` always refer to the latest `check` you have done. There is no possible ambiguity.

**Comment by quite** [comment]
> The only entry that is constructed according to the RSS spec is 4.10. Why only that one, beats me.

Right, I'll contact the producer about this.

> In fact, the numbers in `download` always refer to the latest `check` you have done. There is no possible ambiguity.

Ah, tricky! ;)

**Comment by manolomartinez** [comment]
> Right, I'll contact the producer about this.

Let me know what they tell you, and we can take it from there.

> Ah, tricky! ;)

Ha! It's covered in the README, but certainly a proper man page would be much better :) All right, closing for now; once we hear from the revolutions folk we can take this issue for another spin.
