### ISSUE TITLE
New structure -- review requested

### ISSUE THREAD

**Issue by manolomartinez** [manolomartinez/greg#54]
Hello, @Nick, @Narrat, @FilipBB: I've pushed a `new_structure` branch with what I think is a saner structure for the repo. I was wondering if you could take a look, let me know whether you think it makes sense, or some other thing would make more sense.

Thanks!
M

**Comment by FilipBB** [comment]
Looks good to me, maybe pretty_print() should be moved to auxiliary functions? Or merge it into the "info" command? It doesn't seem to be used anywhere else, and that would keep commands.py to strictly the commands greg implements on the command line.

**Comment by Narrat** [comment]
Looking good to me, too.
What could also be done is to rename the two functions in aux which doesn't follow the general naming convention? (htmltotext --> html_to_text; FeedburnerDateHandler --> feedburner_date_handler)

**Comment by manolomartinez** [comment]
Thanks, this is now in master, with both your suggestions accepted.
