### ISSUE TITLE
First sync zero

### ISSUE THREAD

**Issue by zouhair** [manolomartinez/greg#55]
It seem that "firstsync = 0" doesn't work, it would be nice to have the first sync download nothing.

As I am up to date with my podcasts I don't see the need to download them once more.

Thanks for this nice piece of software.

**Comment by manolomartinez** [comment]
Hello, one way of doing what you want is `greg edit -d <today's date in the format YYYY-MM-DD> nameoffeed`.

I agree that this is somewhat cumbersome. One easy modification I was thinking of is introducing a `now` keyword so that one could do `greg edit -d now nameoffeed`.

**Comment by zouhair** [comment]
Thanks

Or maybe just a "firstsync = 0" option to not download anything at first sync.

**Comment by manolomartinez** [comment]
Yeah, conceptually I think `--downloadfrom` is a better fit, but I'll see if I can fix `firstsync` so that it does the obvious thing for zero.

**Comment by manolomartinez** [comment]
So, now you can do `greg edit -d now yourfeed` and this will move your feed to the current time without downloading anything. 

Getting `firstsync = 0` to behave in the way you expected is rather more difficult than I have anticipated. I might get to it, but not now. Please let me know if the new "now" keyword behaves as expected.

**Comment by zouhair** [comment]
Thanks, could you please update the pip version so I can try it?

**Comment by manolomartinez** [comment]
Done. Note that, if you wish, you can install directly from the repo by using `pip install --user --upgrade git+https://github.com/manolomartinez/greg`.

**Comment by zouhair** [comment]
Thanks a lot, yes `greg edit -d now yourfeed` works great.

Now you just need to add it as an example in your README.md

**Comment by manolomartinez** [comment]
Maybe check the README beforehand?
