### ISSUE TITLE
Wipe unwanted ID3 tags

### ISSUE THREAD

**Issue by josswright** [manolomartinez/greg#57]
I'm finding a few podcasts that I download that have track numbers in them, for some reason, that I don't want. I tried setting the tag_track to an empty string, but that causes an error. Is there a way to wipe unwanted id3 tags in downloaded files?

I could see two ways of doing this:
1) Have a {none} placeholder that caused that tag to be wiped.
2) Have an option to wipe all tags from a file before writing only the specified ones.

**Comment by manolomartinez** [comment]
Hi Joss,

I think adding `tag_track=` to the relevant section in `greg.conf` should now work. Please let me know if this is correct.

**Comment by manolomartinez** [comment]
I assume that my fix did work. Closing for now. If am wrong please let me know and I'll reopen it.
M
