### ISSUE TITLE
Tags are not applied to the downloaded file

### ISSUE THREAD

**Issue by SR-G** [manolomartinez/greg#62]
Let's say I already have a podcast "A.mp3"
I download it again through greg, which will names the new file "A.mp3_". At this point everything is fine.
But if tags are activated, then it is the "A.mp3" which is altered and not the "A.mp3_" downloaded file.

For example, i had that file (0 size):

```
-rw-r--r-- 1 root   root    0 2015-10-20 17:28 229214750-podcastscience-233-la-these-de-micmaths.mp3
```

After redownloading it through greg, i got : 

```
-rw-r--r-- 1 root   root    92M 2016-09-18 09:58 229214750-podcastscience-233-la-these-de-micmaths.mp3_
-rw-r--r-- 1 root   root    176 2016-09-18 09:58 229214750-podcastscience-233-la-these-de-micmaths.mp3
```

The 176 bytes are just the ID3 tags written by greg in the first "0 size" file. It is the newly downloaded file (with the _ suffix) that should have received the new tags.

**Comment by Joeslavins** [comment]
I have the same issue, off all the files that were created only the first one has the tags and unfortunately that is the file that hasn't completed downloading.  

```bash
230576907-linear-digressions-kalman-runners.mp3_
230576907-linear-digressions-kalman-runners.mp3__
230576907-linear-digressions-kalman-runners.mp3___
230576907-linear-digressions-kalman-runners.mp3____
230576907-linear-digressions-kalman-runners.mp3_____
230576907-linear-digressions-kalman-runners.mp3______
```

**Comment by manolomartinez** [comment]
All right, I think this should be fixed now. If you could please test the tip of the master branch, let me know if I am right.

Thanks for reporting,
Manolo

**Comment by manolomartinez** [comment]
I am going to go ahead and close this, as I think it is solved. Feel free to reopen it if I am wrong.

Manolo
