### ISSUE TITLE
Configuration of downloaded files names for each podcast

### ISSUE THREAD

**Issue by SR-G** [manolomartinez/greg#63]
I may be wrong, but i really don't see/understand how to rename downloaded files with greg ?
I would need that feature for some podcasts and not all of them.

Indeed, i have some podcasts where i want to keep the (clean) original filename, but i have a very few ones with quite messy non-standardized filenames. For them i would wish to rename them let's say with just the date.

So how to configure the podcast sections in greg.conf to define the mask of the downloaded files for a given podcast ?

**Comment by SR-G** [comment]
Ok so i suppose i can't do that with the "greg" internal download handler and that i have to use : 

```
[The Tim Ferriss Show]
downloadhandler = wget {link} -O {directory}/{date}.mp3
file_to_tag = {date}.mp3
```

Maybe it should be written down somewhere in case someone else needs to do the same.

**Comment by manolomartinez** [comment]
Right, the internal download handler is very simple indeed.
