### ISSUE TITLE
changing filename on download

### ISSUE THREAD

**Issue by fivetwonine** [manolomartinez/greg#70]
Maybe I'm missing something, but reference is made to changing the filename of the downloaded file in lines 26&27 of greg.conf but I can't figure out how to do this.

I am having problems with a podcast, for which all of the episode files are called "media.mp3" and are stored in unique folders on the host server. (http://rss.acast.com/adambuxton)

I can change the download handler to wget and mod the filename using the -O switch, but then subsequent operations to tag the file (using staggger) fail with error: FileNotFoundError: [Errno 2] No such file or directory: '/podcasts/media.mp3' Stagger is looking for the original filename.

Any suggestions greatly appreciated.

**Comment by manolomartinez** [comment]
Hi, if you change the filename, then you need to tell greg:

`file_to_tag = <your new name>`

This is described in lines 141-147 of `greg.conf`. Is this what was tripping you up?

M

**Comment by fivetwonine** [comment]
M,

Yes, that was it exactly. I managed to figure that out.

Should have closed or deleted my post, thanks for the response.

On 27 Jan 2017, at 14:08, manolomartinez <notifications@github.com> wrote:

Hi, if you change the filename, then you need to tell greg:

file_to_tag = <your new name>

This is described in lines 141-147 of greg.conf. Is this what was tripping you up?

M

**Comment by manolomartinez** [comment]
No problem. Glad you solved it.
