### ISSUE TITLE
Handling basic authentication?

### ISSUE THREAD

**Issue by lardconcepts** [manolomartinez/greg#71]
I'm wondering about the best way to handle feeds where the feed and mp3 require basic authentication.

Currently, the only thing I can think of is to setup nginx as a proxy.

Is there a more pythonic or different/smarter way to handle this?

**Comment by manolomartinez** [comment]
I am afraid greg cannot help you with this at the moment. You are not the first person to request something like this; I will look into it.

M

**Comment by manolomartinez** [comment]
duplicate to #49
