### ISSUE TITLE
TypeError: 'UnknownFrame' object is not iterable

### ISSUE THREAD

**Issue by martinoj2009** [manolomartinez/greg#91]
I'm trying to download CoderRadio, but when I do it gives me an error saying I have no Internet connection, but it'll download other podcasts just fine. I then switched the download manager to wget, but now I get:

Checking CoderRadio...
Downloading Episode 304: No Bad Guys Only Survivors -- 7ba5bb81-338a-4cd6-b2ba-4d1d0b4000e6.mp3
--2018-04-15 21:35:41--  https://aphid.fireside.fm/d/1437767933/b44de5fa-47c1-4e94-bf9e-c72f8d1c8f5d/7ba5bb81-338a-4cd6-b2ba-4d1d0b4000e6.mp3
Resolving aphid.fireside.fm (aphid.fireside.fm)... 96.126.99.139
Connecting to aphid.fireside.fm (aphid.fireside.fm)|96.126.99.139|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://audio.fireside.fm/podcasts/audio/b/b44de5fa-47c1-4e94-bf9e-c72f8d1c8f5d/episodes/7/7ba5bb81-338a-4cd6-b2ba-4d1d0b4000e6/7ba5bb81-338a-4cd6-b2ba-4d1d0b4000e6.mp3 [following]
--2018-04-15 21:35:42--  https://audio.fireside.fm/podcasts/audio/b/b44de5fa-47c1-4e94-bf9e-c72f8d1c8f5d/episodes/7/7ba5bb81-338a-4cd6-b2ba-4d1d0b4000e6/7ba5bb81-338a-4cd6-b2ba-4d1d0b4000e6.mp3
Resolving audio.fireside.fm (audio.fireside.fm)... 104.25.21.5, 104.25.20.5, 2400:cb00:2048:1::6819:1405, ...
Connecting to audio.fireside.fm (audio.fireside.fm)|104.25.21.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 45783800 (44M) [audio/mpeg]
Saving to: ‘/mnt/media/Podcast/CoderRadio/7ba5bb81-338a-4cd6-b2ba-4d1d0b4000e6.mp3.1’

7ba5bb81-338a-4cd6-b2ba-4d1d0 100%[==============================================>]  43.66M  3.02MB/s    in 12s

2018-04-15 21:35:56 (3.73 MB/s) - ‘/mnt/media/Podcast/CoderRadio/7ba5bb81-338a-4cd6-b2ba-4d1d0b4000e6.mp3.1’ saved [45783800/45783800]

/usr/local/lib/python3.6/site-packages/stagger/tags.py:616: UnknownFrameWarning: CTOC: Unknown frame
  warn("{0}: Unknown frame".format(frameid), UnknownFrameWarning)
/usr/local/lib/python3.6/site-packages/stagger/tags.py:616: UnknownFrameWarning: CHAP: Unknown frame
  warn("{0}: Unknown frame".format(frameid), UnknownFrameWarning)
/usr/local/lib/python3.6/site-packages/stagger/frames.py:109: DuplicateFrameWarning: CHAP: Duplicate frame; only the first instance is kept
  DuplicateFrameWarning)
/usr/local/lib/python3.6/site-packages/stagger/tags.py:711: FrameWarning: CTOC: Ignoring incompatible frame
  FrameWarning)
Traceback (most recent call last):
  File "/usr/local/bin/greg", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/greg/parser.py", line 138, in main
    function(vars(args))
  File "/usr/local/lib/python3.6/site-packages/greg/commands.py", line 176, in sync
    downloaded = feed.download_entry(entry)
  File "/usr/local/lib/python3.6/site-packages/greg/classes.py", line 331, in download_entry
    aux.tag(placeholders)
  File "/usr/local/lib/python3.6/site-packages/greg/aux_functions.py", line 198, in tag
    stagger.util.set_frames(podpath, {tag: metadata})
  File "/usr/local/lib/python3.6/site-packages/stagger/util.py", line 111, in set_frames
    tag.write(filename)
  File "/usr/local/lib/python3.6/site-packages/stagger/tags.py", line 655, in write
    tag_data = self.encode(size_hint=length)
  File "/usr/local/lib/python3.6/site-packages/stagger/tags.py", line 1012, in encode
    frames = self._prepare_frames()
  File "/usr/local/lib/python3.6/site-packages/stagger/tags.py", line 706, in _prepare_frames
    for frame in self._frames[frameid]:
TypeError: 'UnknownFrame' object is not iterable

**Comment by martinoj2009** [comment]
If I turn Tags off then it works.

**Comment by manolomartinez** [comment]
I'm sorry, I've been mostly unresponsive with greg due to lack of time. I have a bit more time now for this. In the (perhaps unlikely) case you are still interested in this issue, let me know and I'll get to it. Closing in the meantime.
