### ISSUE TITLE
Can't download "This Week in Linux"

### ISSUE THREAD

**Issue by thomasboehm** [manolomartinez/greg#92]
Hi,

I hope this is the right place to ask my question. I use greg with a few podcasts. Some are on Youtube and some are not. My helper script looks whether the video is on Youtube or not and uses either wget or youtube-dl accordingly. So far so good.

Now try to add "This Week in Linux" with the feed url https://tuxdigital.com/category/shows/this-week-in-linux/feed. I added the feed with

`greg add "This Week in Linux" https://tuxdigital.com/category/shows/this-week-in-linux/feed`

and ran

`greg check -f "This Week in Linux"`

This returns a list of 15 episodes. When I try to download 1 episode it just does nothing. No error message, it just returns to the prompt. The helper script does not get executed.

~~The same happens when I use their Youtube channel~~

~~https://www.youtube.com/feeds/videos.xml?channel_id=UCmyGZ0689ODyReHw3rsKLtQ~~

Am I doing something wrong or is there a problem with these particular feed?

Edit: The Youtube feed works. I had a typo in my config.

**Comment by Strubbl** [comment]
You are using a feed without enclosures. If you want only the mp3s or oggs, use the appropiate feed. If you want the videos, you need to add the youtube's feed for that channel. The feed URLs can be found e.g. [here](https://tuxdigital.com/2018/10/episode-42-this-week-in-linux/)

**Comment by thomasboehm** [comment]
I have "ignoreenclosures = yes" in my config for the Youtube channel and as I wrote, Youtube works. 

I'm having problems with the RSS feed on their site. I want the video feed. After adding "ignoreenclosures = yes" to that, it seems to download the video and the description, but the video file only contains the HTML code of the feed's site. The URL I'm using is the one from my first post.

**Comment by Strubbl** [comment]
just directly add the youtube channel of This Week in Linux to greg

**Comment by hansenhans** [comment]
Yes, that's what I'm doing right now. But I thought you might want to fix a bug in greg, if it is a bug. It also could be a problem with the feed. I don't know.

And who knows if Google decides in the future to disable the RSS feeds for the Youtube channels. Wouldn't be the first time they do something like this...

**Comment by thomasboehm** [comment]
Yes, that's what I'm doing right now. But I thought you might want to fix a bug in greg, if it is a bug. It also could be a problem with the feed. I don't know.

And who knows if Google decides in the future to disable the RSS feeds for the Youtube channels. Wouldn't be the first time they do something like this...

**Comment by manolomartinez** [comment]
Hey, I've been looking into that feed, and the information it provides does not include the youtube links, so greg's behavior seems entirely correct here, unless I am mistaken. Closing for now, but feel free to reopen if I am missing anything.

**Comment by thomasboehm** [comment]
Hi,

I think you have mistaken me. I never said that the feed contains Youtube links. Youtube is what I'm using as a "workaround" at the moment. But I rather not rely on this as Google is known for changing API's  etc.

The feed https://tuxdigital.com/category/shows/this-week-in-linux/feed contains the following:

`
...
<link>https://tuxdigital.com/2019/04/episode-63-this-week-in-linux/</link>
...
`
This link is not the direct link to the video. This link leads to the web page of the episode which contains the video among other things.

So my question was, if greg behaves correctly and the problem lies within the way this feed presents the links or greg does it wrong.

**Comment by manolomartinez** [comment]
I'd say greg is doing the right thing. It's impossible for it to know that it should follow through that webpage onto a video link. 

On the other hand, if you'd absolutely prefer to use the official feed, it should be relatively easy to create a custom downloadhandler that read that webpage, retrieved the video link and downloaded it. Does that make sense?

**Comment by thomasboehm** [comment]
ok, thanks. I'll look into that.
