### ISSUE TITLE
Downloaded filenames missing most of their content with default settings (Windows)

### ISSUE THREAD

**Issue by azmr** [manolomartinez/greg#94]
I tried downloading files from 3 different podcasts and the output name for the file strips everything before the last space:
e.g. `#1 Welcome to the Future of Coding -- audio.mp3` -> `audio.mp3`

This happened with both `sync` and `download`

Let me know if there are other details you'd like me to provide.

The software seems cool apart from this, thank you for your work on it!

**Comment by manolomartinez** [comment]
Hey! I am sorry I haven't been very active with greg. Hopefully this'll change now. Would you mind providing me with the information for the feed that does this? Have you changed anything in greg's `config` file?

Thanks for reporting
