### ISSUE TITLE
Download using title of spefic podcast

### ISSUE THREAD

**Issue by 12nick12** [manolomartinez/greg#96]
Is there a way to download using title of specif podcast since one of the podcasts I follow keep the file the same name.

**Comment by runrin** [comment]
try something like this at the end of your greg.conf:
```
[Foo]

# uncomment this if you are tagging the files
# file_to_tag = {filename_title}.mp3

downloadhandler = wget -q {link} -O {directory}/{filename_title}.mp3
```
