### ISSUE TITLE
Question: How are previously downloaded podcasts recorded?

### ISSUE THREAD

**Issue by WaterSibilantFalling** [manolomartinez/greg#97]
In greg, how are the previously downloaded podcasts recorded? 

in the greg/data directory there is a collection of feeds. Is something added to the feeds to indicate which episodes have been downloaded already? 

Thanks for any pointers.

**Comment by Strubbl** [comment]
i have the defaults in my `~/.config/greg/greg.conf`. So it's the path at `~/.local/share/greg/data/`

**Comment by WaterSibilantFalling** [comment]
No. 

in your  ~/.local/share/greg/data/ there are two files: 
- Data, which is a list of podcasts. It is not a list of episodes, and 
- feeddump, which is a huge collection of rss feeds, all cat'ed together.

I asked in my original post: 

> Is something added to the feeds to indicate which episodes have been downloaded already?

If not, then How are previously downloaded podcasts recorded?

**Comment by Strubbl** [comment]
Yes.

in data/ dir is a file for every podcast where status is saved

**Comment by WaterSibilantFalling** [comment]
Not for me. 

In my current greg install, and in the last (I stored a disc image of my last laptop) there was no file named 'dir' in the data directory.  There are only two files (1) data/data and (2) data/feeddump

But I'll accept that you are correct. 

So now: How to get the 'dir' file to appear in my greg data dir, so that the status of downloaded podcasts can be recorded? 

I'll look at the config file, again, this evening.

**Comment by WaterSibilantFalling** [comment]
I just looked at the greg config file. 

There is nothing about where to store a record of the downloaded podcasts. 

You know, I should just look at the code.

**Comment by AlmightyFrog** [comment]
I am not sure what you are searching for, but I do use a docker for it and have my folders mapped to /data for the videos and /config for the configuration with following lines in greg.conf:

> [DEFAULT] 
>
> Data directory = /config/meta/
> Download directory = /data/

With this settings in my /config/ there is greg.conf and in /config/meta/ there is a file for each tracked subscription.

**Comment by Strubbl** [comment]
> So you have said "Yes", so you are stating that in your greg/data directory there is a file called 'dir' that records that each podcast downloaded.
> 
> Not for me.

For me neither. That's what you have interpreted instead of. 

i wrote

>> in data/ dir is a file for every podcast where status is saved

dir stands for directory. so see my ls:

```
$ ls -l ~/.local/share/greg/data/
total 792
-rw-r--r-- 1 strubbl strubbl   2375 Apr  3 12:25 podcasta
-rw-r--r-- 1 strubbl strubbl   3359 Feb 12 01:06 podcastb
-rw-r--r-- 1 strubbl strubbl   3877 Apr 17 06:03 data
-rw-r--r-- 1 strubbl strubbl  31956 Apr 10 01:26 podcastc
-rw-r--r-- 1 strubbl strubbl  80433 Feb 18 20:36 feeddump
```

podcasta .. podcastc stands for the name i have given to my subscription.

I don't know anything about you setup and why you don't have those files. Your issue is described so superficial. Don't expect a magic guess to solve your problem in an unmaintained project.

**Comment by WaterSibilantFalling** [comment]
Thanks, that's it. 

You have correct additional files in your greg/data dir. I don't have those (one for podcasta, podcastb . . . )

Thank you.
